---
title: Tactical Fortification Angelina-Hoederer Guide
description: A comprehensive guide to the Tactical Fortification Angelina-Hoederer strategy in IS5, covering drafting, strategy, and boss fights.
---

<div class="back-button-container">
  <a href="/is5-sarkaz/overview/" class="back-button">
    <span class="back-arrow">←</span>
    <span class="back-text">Back to IS5 Overview</span>
  </a>
</div>

# Foreword
The following article is a direct translation of the transcript of the Facing Souls 18 ED2+4+5 [Angelina Hoederer Tacfort comp](https://www.bilibili.com/video/BV1FDKEzXEPJ/) strategy showcase video (BV ID: BV1FDKEzXEPJ) originally produced by the CN stratey group [重辅猫咖](https://space.bilibili.com/3546902855420627) (Tacfort Cat Café) (all rights reserved) and translated by me. The strategy discussed here assumes a TactFort comp operating under tournament-style IS5 conditions (i.e Facing Souls 18, ED2+ED4+ED5, no Blueprint, no Wiš’adel) and by no means should constrict your options for casual play. Hence, the audience is assumed to have a solid foundational knowledge of IS5, but in case you aren’t well informed, here’s a prerequisite glossary which contains the necessary vocabulary to discuss IS5 at an advanced level.

## Prerequisite Glossary

| Chinese | English | Definition |
| :--- | :--- | :--- |
| 单国王/新枪 | 1x King’s | King’s Lance |
| 双国王/冠冕 | 2x King’s | King’s Lance + King’s Crown |
| 三国王 | 3x King’s | King’s Lance + King’s Crown + King’s Armour |
| 体系/构筑 | comp | A systematic and specific set of draft plans, squad, and Fated Encounter relic that together form a coherent overall strategic plan. |
| 紧急（关卡） | EM | emergency stage |
| 强控/强控制 | hard control | Control effects that make the enemy unactionable including stun, freeze, levitation, etc. |
| 鬼图 | hard stage(s) | A hard non-boss stage |
| 隐藏/鸭狗熊鼠 | hidden animals | Duck Lord, Teary Detective, Gopnik, Fatty |
| 穷局/胡局 | highroll/lowroll run | A run with high/low power due to drafts, relics, thoughts, pathing, ending RNG, etc., or the lack thereof |
| 本家 | in-classes | The two classes which get a Hope discount for a particular class squad |
| 普通（关卡） | NM | normal stage |
| 无藏无漏 | NCL | No Collectables nor Leaks |
| 无藏无板无漏 | NFCL/NTCL | No Foldartals/Thoughts, Collectables, nor Leaks |
| 一击线 | one-shot threshold | The damage it takes to one-shot an operator or enemy, a useful metric to measure survivability |
| 外援 | out-class(es) | Classes which do not get a Hope discount for a particular class squad |
| 战力 | power | The general ability for your current combination of squad, drafts, relics, thoughts, etc. to take on hard stages. |
| （战力）上限/下限 | power ceiling/floor | The maximum/minimum power of an operator. |
| 进度焦虑 | progress anxiety (typically that of Lamp relics) | Since the required power scales with a run’s progress, having too little progress on Lamp relics (hands, books, King’s, Toy, Chalice) or other forms of power would mean you’re unable to take harder stages (e.g. Lamp comps can’t realistically rob shop with solo King’s). Hence, anxiety here refers to the sense of urgency in obtaining a certain Lamp progress or level of power by a certain point in the run. |
| 吃藏能力 | relic scaling | The degree to which an operator’s power increases due to relics (e.g. Wiš’adel S2 is buffed significantly by relics, but her S3 gains less improvements relative to its original strength) |
| 资源回收 | resource recycling | The ability of an operator to generate additional power over the run to cover their own costs as well as make additional profit (e.g. Amiya costs 4 Hope and two nonessential tickets in Tact Fort. In exchange, she profits lots of plans, allows you to take harder but more profitable paths, counters ED2 and ED4 with her True damage, etc., thereby generating more resources than what she costs). |
| 回转 | skill cycle | Skill duration + downtime, useful concept for timing skills correctly |
| 软控/软控制 | soft control | Control effects that leave the enemy actionable including bind, slow, MSPD reduction, etc. |
| 卡刺 | stalling for Spines | Stalling the last enemy on the stage and defeating them as late as possible (typically with a damageless operator such as S2 Cuora or Soul Escort Kafka) to buy time for DPS ops to destroy Spines of Epoch for valuable Plans. |
| 总伤 | total damage | The sum of all damage dealt during a skill, implied to be against a single target unless stated otherwise |
| （道中）过渡 | (en route) survivability | The ability of an operator, comp, relic, etc. to keep run alive until the bosses and gain more power in the process |

## Introduction
In the latest Theurgy Cup, player **msc** utilised a coherent comp, logical techniques, and strong foundational skills to demonstrate the TactFort squad in IS5. However, the ending RNG, lack of difficult stages, and slight highrolling relics seem to give false impressions that TactFort is used not for meta’s sake, “I could’ve won if I piloted that run”, or that “it’s worse than First Class squad”. Please allow me to break these stereotypes in this guide, introducing the high win rate 30 Hope cost: Angelina Hoederer TactFort comp.

Angelina Hoederer TactFort is a comp that requires very little Hope (lower than First Class squad), counters the endings well, has a high power floor, requires extremely few powerful 6-stars, has low progress anxiety, and is filled with niche tech and fun. Although the TactFort comp has some prerequisite build costs and can be quite hard to play, you’ll find it to be immensely powerful and pleasing.

A viable comp must have the ability to recycle resources early game to snowball, the ability to draft in accordance to a sensible planned Hope curve and planned ticket distribution, the ability to take hard maps even with low draft power and low Lamp progress, and have various different strategies available to counter boss stages. The Ange Hoederer comp is able to fulfill all of these conditions. Shown below are the four components of TactFort’s drafts. All TactFort comps generally follow the pattern of 9 Hope’s worth of in-class drafts + common Vanguards/Healer/Specialists/Amiya + high quality 6-star out-class drafts. While secondary in-class 6-stars and some out-class 6-stars have useful niches, they’re rarely drafted in practice because they’re unable to fulfill the aforementioned points. The draft order in a typical run is first the comp core of Ange + Hoederer, then other components, and finally out-class draft Kal’tsit. But of course, you can alter this based on your own understanding and the actual game state.

## The Angelina-Hoederer Core
The core of the comp is **Angelina** with her powerful IS module providing strong hard control, fast cycling, high hitcount, high hit frequency, and extraordinary damage output. Thanks to Ange’s control and quality DPS, this comp has a relatively low progression anxiety, crushes the first three floors, takes out the hidden animals without any progress, and survive en route. When including her IS module and the tech tree, S2 has a total damage of 49.6k and S3 has 34.4k against non-levitating targets. S2 has a total damage of 83k and S3 has a total damage of 103k against levitating targets. Even just the Buckler Hand provides Ange with a strong resistance against Epochs like Oddities and Catastrophes. On F3/4/5, Ange can challenge hard stages with low progression, most notably: relicless EM Motorised Squad solo carry, Buckler NM Elusive Merc, Lance NM Chaos, double kings NM Frequent Disputes, and double kings and +20% external buff NM Rhine Guardians, etc. For the endings, Buckler Ange with her high hit frequency and RES debuffer **Haze** can easily lower the Boss’ HP in 15 seconds to provide an opportunity for teammates to finish them off. Her Anti-Gravity antics bring three methods for TactFort to shift (bully) **Theresis**: **Wild Mane**, **Mint**, and **Rope**. Furthermore, Ange has a high relic scaling, which means she gains significant improvements from a variety of relics, such as Slave Hunter or SP recovery relics. The comp is allowed to lean more heavily into physical damage relics since the Buckler Hand scales in power as the enemy increases in HP, so Ange can still maintain a strong en route survivability despite having few relics.

**Hoederer** is Ange’s best out-class teammate. As a common draft in all Lamp comps, he has a passive 31% physical Sanctuary, high HP, hard control, and serves as an excellent blocker with strong auto attack damage. Hoederer’s traits complement Ange, who lacks damage output during her downtime, is quite frail, and plateaus in damage against levitation-resistant or high RES enemies, hence greatly improving en route survivability and countering the endings. Hoederer can solo p2 and 3 of t1 egg ED5. With additional out-class drafts such as **Kal’tsit**, the comp can even take on t3 egg with only three 6-stars.

## In-Class Drafts
In-class operator **Bassline** is a strong draft, costing only 1 Hope while using only 1 deployment slot. In exchange, Ange gains a sorely desired high quality blocker and healer in the early game, with high RES to combat against the prevalence of Arts damage in IS5 and built-in healing to decrease the healing pressure. His module’s 15% damage reduction gives him extremely strong survivability, being able to tank and heal in many stages en route. S2’s short windup allows Bassline to be deployed into Marks of Epoch and still activate his skill. Not attacking for 60s has some interesting uses, such as stalling for Spines or not activating certain enemies. Extra RES from S2 also counters many enemies for a strong performance en route and in endings. For ED2, standard King’s plus Rise and Fall Bassline plus Hoederer can straight up tank Theresis. For ED4 p3, Bassline can heal the Flames as well as tank damage. For t3 egg ED5, Bassline can tank Manfred in p2 as well as Amiya and enemy Kal’tsit in p3.

In-class operator **Blitz** is also a strong control draft with a large range, zero-windup stun to counter the low-altitude hovering enemies in Motorised Squad, Frequent Disputes, and Rhine Guardians, as well as flying chests. Hence, Blitz’s large range stun is a key component in this comp’s shop-rob strat. The Silence from his skill prevents explosion damage from exploding slugs and the Rhine Traffic Tower. His anti-invis mod also provides a first strike initiative against invisible enemies in Heretics and Regular Army.

In-class operator **Quercus** is an excellent draft for healing, using her Sanctuary, low attack interval, and big heals to eliminate dependence on Medic tickets. She reduces healing pressure and enables many survival and tanking-based strats, such as countering the healing pressure in Chaos, zero progress Battle for Survival Kal’tsit blocker switch strat, and providing survivability in the three endings. Furthermore, Quercus with high ASPD and Buckler hand can become an excellent damage dealer, notably exemplified in Chaliceless damage output against Theresis p2.

## Out-Class Drafts
**Amiya** is one of TactFort’s most important out-class drafts with her form changes and excellent high value True damage, all for a low cost, to help snowball en route. Her form changes are useful in a variety of stages, such as Guardmiya in Simulated Skirmish helping with blocking, executing the Mortars, and destroying the Spine, or Castmiya’s powerful True damage to hard counter Catastrophe spines, and finally Medmiya as a healing-damage two-in-one to save deployment resources. That aside, early drafts all serve to recover resources, Amiya’s True damage and Bassline’s cheap stalling are able to deal with the majority of hidden animals and Catastrophe spines.

**Greyy the Lightningbearer** is a common damage output draft in IS5 with his high hitcount, AoE soft control, and strong relic scaling all combining to make him a famed AoE damage dealer offskill.

**Haze**, the Goddess of RES debuffing can make use of otherwise useless Caster tickets. Her unconditional -30% RES debuff provides a significant buff for p3 Quilon finishers (1 million damage increase over 15 seconds).

**Surfer** is an excellent DP generator and additional damage output, her S2 has good resistance against Crystal Mystery to help against TactFort’ many high-DP drafts. Thanks to Lamp’s ASPD buffs, she can carry the entire squad’s DP requirements in spite of ED2 and ED5 relics.

**Fast-redeploys** can block Theresis’ orbs and bounce Amiya’s orbs, which is universal across all comps.

With the help of Angelina’s Anti-Gravity, the three viable shifters for this comp **Rope**, **Wild Mane**, and **Mint** widens TactFort’s scope of strategies available for ED2 and uses up what would otherwise be useless tickets. This is most true for Rope and Wild Mane. The former not only counters ED2, but also has an excellent matchup into Motorised Squad, Chaos, Timeworn Tensions, Wrecked Academy by leveraging her shifting capabilities and as a high-DEF and dodging high tile operator. The latter only costs 1 ticket to, in combination with Anti-Gravity, push Theresis to his minimum damage reduction. If neither are available, E2 Mint may be drafted to pull Theresis to a specific location to allow a teammate on the safe high tile to finish him off.

**Kal’tsit**, as a generally strong operator in Lamp comps, is the last piece to the TactFort puzzle, being able to replace some of Hoederer’s roles if he is yet to be drafted. Her strong True damage output and quality blocking can similarly provide damage output en route and act as a finisher in endings. **Mon3tr** and all of her fellow summons ignore the sealing mechanic in ED5, which makes laneholding, baiting binds, and outputting damage quite convenient.

In addition to these primary drafts, there is also a plethora of secondary drafts: **Tin Man’s** Enfeeble, healing, and Mental Toll increase, **Shamare’s** ATK debuff and as a Buckler user, **Ashlock/Horn** to assist Greyy the Lightningbearer in ED2 and ED4 laneholding, **Deepcolour** to bait bind in ED5, **Gnosis** for hard control and Fragile buffing, **Ethan’s** bind, **Mlynar’s** taunt and high damage output, **Mudrock** to tank Theresis, etc. The primary in-class drafts plus Hoederer and Kal’tsit as out-class drafts plus secondary drafts when suitable is a display of the self-coherent nature of the TactFort comp.

## Tragodia and Handmixing
[TN: Tragodia isn’t out on EN yet, but this is still worth a read on handmixing] Here, we need to stress why **Tragodia** isn’t a part of our primary drafts: comps with a Hand will inherently lag in Lamp progress. If another Hand is to be added on top of that and F3 lacks a Bosky for development, we may only be barely up to triple King’s by the end of F4, even if a shop had a King’s Legacy. Without that Legacy, we might not even have triple King’s by F5. Simultaneously, we must take as many combats as possible because of our lack of tickets. That, plus the pressure of taking endings and Lamp progress, means we require more nodes than are available. Tragodia mainly ensures en route survivability as well as having a strong performance in ED5. Ange start into an early Tragodia draft is guaranteed to steal Hope reserved for Hoederer, Surfer, Kal’tsit, and Greyy the Lightningbearer, but in exchange, we only receive protection against some hard EM stages and Regular Army (Ange is lacking in anti-air). Lamp requires a lot of nodes to progress, so even a slight lowroll removes the possibility for a t3 egg. It’s best to have drafted Kal’tsit and Mlynar if going for t3 egg. Therefore, the Ange comp must already have obtained Commandments/Chalice or Mystery Hand in order to draft Tragodia from the F6 shop to counter t3 egg. Otherwise, Tragodia draft is not recommended.

For a detailed advanced description of the comp’s combos and operators’ traits and usage, check out *Tacfort Cat Cafe member Yaya’s article*, we won’t discuss it further here. Now, let’s take a look at our comp’s operational strategies.

## Operational Strategy
We draft **Quartz**, **Ange**, and **Purestream**, as our starters and pick 2 Plans as our F3 buff. As a Crusher, Quartz has a high HP and damage output, so she performs better en route in the Ange Hoederer comp. Purestream with her a large range and high relic scaling is primarily a draft for the endings. We can opt to take triple combat for extra hope if we will have 1-2 excess Plans remaining afterwards. For drafting order, we prioritise Amiya and Bassline, then Quercus. Surfer may be drafted early if the Hope curve allows for it, but otherwise should be delayed. Tin Man may be drafted before the F2 Scout if it doesn’t affect the Hope curve for either Amiya or Bassline, otherwise we must draft Rope and Gravel to prevent a Specialist ticket deficiency later on. Kal’tsit may be drafted before Hoederer if he is late to be drafted depending on the current Hope, Collectables, King’s progress, remaining combat nodes, and other factors contributing to the overall gamestates. Otherwise, Hoederer is still higher in priority.

Ange Hoederer TactFort must take plenty of combats to develop a complete draft and Collectables progress when Plans are reasonably available. Thus, the comp typically won’t take Petal on F3, being a consideration only when there is a Bosky or extra Hope. If F3 has a Bosky, then we must take it for the extra nodes, combats, and King’s progress. Ange Hoe TactFort typically takes Petal on F4, where there’s a 76% spawn rate for a natural Lost and Found, or 87% when refreshing Wish Fulfilleds into LnF. The ED5 Ghost can be taken whenever suitable; Buckler Ange can easily deplete the Ghost’s HP. The advantage being we can defeat it whenever we choose, but on the other hand, farming Collectables from the Ghost requires more complex strategies to prevent Angelina from hitting it. Usually, we need to reserve 1-3 Plans when entering F2 and 2-5 Plans when entering F3/4/5, enough to take a vertical path and plan for endings and development. As for a general shopping plan, Ange doesn’t need many Collectables bought for her, but rather Greyy the Lightningbearer, Hoederer, and other drafts do need additional power. Consider buying SP recovery relics and multiplicatively buffing Collectables as they improve Ange significantly. Lamp progress Collectables like Buckler, Armour, Legacy, and powerful relics like Soul Binding Bone have higher priority as shown. Typically, we spend 20 ingots on each page of the shop, if a Lamp progress relic doesn’t appear with an EX tier relic, buy it. If both are present, then Buckler has decreased priority. EX tier relics being: Soul Binding Bone, Arch Glyph, Song to Make A Tenacious Mind, Anchor For Five Seconds Ago, and Herr Hraaselsuher.

Ange doesn’t require many buffs to take on Boats, the proper placement and solo feeding allows Ange to cycle three S2s with Buckler to dominate the Boats. She can take F3 Boats with Buckler and F4/5 Boats with Lance. Much more comfortable to use than other comps who can’t even take boats with triple King’s.

For the negative Collectables, Ange Hoederer doesn’t mind the +3000 DEF much since the comp relies on Ange’s Arts damage in the early game so it only affects Surfer and May. However, it’d be best if it could be traded away since it affects shop rob toplane and Quilon leftside laneholding. -20 SP is more impactful since it messes with skill timings for a comp deeply entrenched in proper skill timings and makes some situations quite untenable. +1 Hope has some impact too as it tightens the Hope curve. +20% stats is just a no, the straight up big number stat buffs are hard to handle for anyone. -30% ATK is the most useless negative Collectable.

For farming Ghost Collectables, every tick of Ange’s levitation damage activates Buckler so the Ghost gets melted quickly. Thanks to our high power floor, we don’t necessarily rely on farming Collectables from the Ghost. Of course, we can still farm Collectables if shields are plentiful, but if it’s impractical, then Ange can quickly melt the Ghost down into a Lingerer.

## Endings Strategies
For ED2 p1, we typically use the standard tanking strategy with **Hoederer** **Quercus** tanking **Theresis** and **Hoederer** **Greyy the Lightningbearer** laneholding (see *msc’s stream VODs*). Against low-survival power King of Sarkaz ED2, we have a **Tin Man** solution, a **Shamare** solution, and a **Rope** permastall solution. If Hoederer is unavailable, **Kal’tsit** can replace him. For p2, we use Ange’s Anti-Gravity antics to decrease weight to shift Theresis, lower his HP with Buckler **Angelina** **Quercus**, **Castmiya** as the finisher, **Hoederer** to lanehold swallowers. If Hoederer is unavailable, we can replace him by cycling **Ange** and **Greyy the Lightningbearer**.

For ED4, we also use the standard strategy: **Quercus** to sustain the entire squad, **Hoederer** S2 to hold rightlane and output damage to **Quilon**, **Greyy the Lightningbearer** to hold leftlane, and **Ashlock/Horn** to assist laneholding when available. The standard p3 finisher comp should send **Ange**, **Bassline**, **Castmiya**, **Purestream**, **Haze**, **Surfer**, and potentially extra damage dealers like **Kal’tsit**. Ange Haze can reduce Quilon to low HP in 15 seconds which drastically reduces the pressure on the damage output required. With suitable Collectables, Castmiya alone is enough to finish off Quilon.

The hard requirements for t3 egg are survival and squad slots, typically at least +130% external HP or equivalent and 10+ squad slots. Lakebed Aegis is a top tier decisive survival Collectable; if you get it early, you can probably start strategising for t3 egg. For more details on operational strategy, head over to *重辅猫咖 member [Sidereum·Caelum](https://space.bilibili.com/697452546/)’s [Theoretical Profitability model video](https://www.bilibili.com/video/BV1VGEozjE39/)* and *msc’s stream VODs*. For specific strategies for each stage, head over to *重辅猫咖 members [Sidereum·Caelum](https://space.bilibili.com/697452546/), [w杰-洁-劫w](https://space.bilibili.com/293758258), and [欧的堵](https://space.bilibili.com/10430014)’s bilibili page* as well as *msc’s stream VODs* and the [*Tacfort Cat Cafe’s bilibili page*](https://space.bilibili.com/3546902855420627).

For t3 egg ED5 p1, **Kal’tsit** **Ange** holds topside and Ange takes out the three boats that hit high tiles, the rest may be leaked. **Greyy the Lightningbearer** solo damage outputs bottomside and can add **Ethan** if available. P2 uses **Bassline** **Hoederer** to hold and tank the middle lane, **Kal’tsit** on bottomside chips **Manfred**, **Ange** **Amiya** defeats **Theresis**, and **Mon3tr** defeats **Manfred** simultaneously. Finally for p3, **Hoederer** solos boss **Amiya**, **Angelina** assists with Goliath and enemy **Kal’tsit**, **Quercus** **Quartz** or another tank blocks Laqermaline, and remember to bait binds asap. Divide and conquer the battlefield to achieve victory.

## Conclusion
All in all, Ange Hoederer TactFort has complex execution, high difficulty, tight timings, and a high cost of learning, but these do not detract from its brilliance. In Theurgy Cup, TactFort serves as a sacrificial slot (and partially as a strategy showcase) thanks to its ability to maintain a stable win rate despite handing over many 6-stars. Whether you’ve tried TactFort before, the Ange Hoe comp will be an entertaining, fulfilling, and coherent comp. With this introductory guide, we hope more IS players will understand the charm of the Tactical Fortification squad.